### ISSUE TITLE
repetitive imports in main.py

### ISSUE THREAD

**Issue by Veeraraju-E** [guangyaodou/ConMU#1]
Hi.

- A small nit - there are repetitive library imports in ConMU/main.py and ConMU/dataset.py . It'd make the code more clean if you could optimize them.
- Nevertheless, great paper and concept!

**Comment by guangyaodou** [comment]
Thank you for pointing this out! Feel free to make any PR to make this more cleaned! Also let me know if you have any questions!

**Comment by Veeraraju-E** [comment]
PR opened
